[ECFS]
QUANTIDADE=1
EMPRESA=1

[CONEXAO]
SERVIDOR=localhost
BANCO=CLICK
USUARIO=sa
SENHA=sys
TIPO_BANCO=SQLSERVER

[GESTOR]
SERVIDOR=localhost
BANCO=CLICK
USUARIO=sa
SENHA=sys
TIPO_BANCO=SQLSERVER

[IMG]
SERVIDOR=localhost
BANCO=LSICLICKIMG
USUARIO=sa
SENHA=sys
TIPO_BANCO=SQLSERVER