[TERMINAL]
NUMERO_TERMINAL=1
NUMERO_FILIAL=1
NUMERO_ESTOQUE=1
NUMERO_SEGUIMENTO=1
SERVIDOR=192.192.192.192
PASTA_RAIZ_LSI=C:\LSI Sistemas\

[BALANCA]
Porta_Leitor=
Porta_Balanca=
Modelo_Balanca=
Modelo_Teclado=

[ETIQUETABALANCA]
CODIGO_INICIAL=2
TAMANHO_CODIGO=6
VALOR_INICIAL=8
TAMANHO-VALOR=5

[IMPRESSORA]
PORTA_PRINT=D\TEXT.TXT

[LICENCA]
CNPJ=

[ECFS]
QUANTIDADE=1
EMPRESA=1

[ATUALIZACAO]
PASTA=C:\LSI Sistemas\ClickUPDate\


[SERVIDORES]
PASTA=C:\LSI Sistemas\LSIClick\servidores cheff\